# generate chemrof-compliant elements from wikidata
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX chemrof: <https://w3id.org/chemrof/>
PREFIX chemrof.data: <https://w3id.org/chemrof/data/>
PREFIX type: <http://www.wikidata.org/prop/direct/P31>
PREFIX Element: <http://www.wikidata.org/entity/Q11344>
PREFIX symbol: <http://www.wikidata.org/prop/direct/P246>
PREFIX atomic_number: <http://www.wikidata.org/prop/direct/P1086>

CONSTRUCT {
    ?iri a chemrof:ChemicalElement ;
      rdfs:label ?label ;
      chemrof:symbol ?symbol ;
      chemrof:atomic_number ?an
}
WHERE {
    ?i type: Element: ;
       rdfs:label ?label ;
       symbol: ?symbol ;
       atomic_number: ?an .

       FILTER (LANG(?label) = "en")

   BIND(IRI(CONCAT("https://w3id.org/chemrof/data/ChemicalElement/", STR(?symbol))) AS ?iri)
}
