PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX chem: <https://w3id.org/chemschema/>
PREFIX type: <http://www.wikidata.org/prop/direct/P31>
PREFIX subClassOf: <http://www.wikidata.org/prop/direct/P279>
PREFIX Isotope: <http://www.wikidata.org/entity/Q25276>
PREFIX Element: <http://www.wikidata.org/entity/Q11344>
PREFIX MonoatomicIon: <http://www.wikidata.org/entity/Q1588896>
PREFIX inchi: <http://www.wikidata.org/prop/direct/P234>
PREFIX hasPart: <http://www.wikidata.org/prop/direct/P527>
PREFIX atomic_number: <http://www.wikidata.org/prop/direct/P1086>
PREFIX neutron_number: <http://www.wikidata.org/prop/direct/P1148>

CONSTRUCT {
    ?i a chem:MonoatomicIon ;
      rdfs:label ?label ;
      chem:inchi_string ?inchi ;
      chem:has_element ?element
}
WHERE {
    ?i (type:/subClassOf:*) MonoatomicIon: ;
       rdfs:label ?label ;
       inchi: ?inchi ;
       hasPart: ?element .
    ?element type: Element: .

    FILTER (LANG(?label) = "en")
       
}
