site_name: "CHEMROF"
theme:
  name: material
  palette:
    scheme: default
    primary: purple
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mermaid2
nav:
  - Introduction: home.md
  - Database: database.md
  - Ontology: ontology.md
  - Schema: index.md
  - Metaclasses: metaclasses.md
  - Credits: credits.md
site_url: https://chemkg.github.io/chemrof/
repo_url: https://github.com/chemkg/chemrof/
