-- semsql views that views/*.sql rely on, with their transitive dependencies,
-- copied verbatim from a semsql sqlite_master (generated by semsql_closure.py).
-- The duckdb sqlite scanner cannot parse every semsql view, so the make target
-- copies only the base tables below and then applies this file.
-- Base tables: statements
CREATE VIEW has_dbxref_statement AS SELECT * FROM statements WHERE predicate='oio:hasDbXref';
CREATE VIEW owl_axiom_annotation AS SELECT
   axpv.stanza AS stanza,
   axs.object AS subject,
   axp.object AS predicate,
   axo.object AS object,
   axo.value AS value,
   axo.datatype AS datatype,
   axo.language AS language,
   axpv.subject AS id,
   axpv.subject AS annotation_subject,
   axpv.predicate AS annotation_predicate,
   axpv.object AS annotation_object,
   axpv.value AS annotation_value,
   axpv.language AS annotation_language,
   axpv.datatype AS annotation_datatype
  FROM
   statements AS axs,
   statements AS axp,
   statements AS axo,
   statements AS axpv
  WHERE
   axs.predicate = 'owl:annotatedSource' AND
   axp.predicate = 'owl:annotatedProperty' AND
   axo.predicate = 'owl:annotatedTarget' AND
   axs.subject = axpv.subject AND
   axp.subject = axpv.subject AND axo.subject = axpv.subject AND
   axpv.predicate NOT IN ('owl:annotatedSource', 'owl:annotatedProperty', 'owl:annotatedTarget', 'rdf:type');
CREATE VIEW owl_some_values_from AS SELECT onProperty.subject AS id,
            onProperty.object AS on_property,
            f.object AS filler
            FROM
       statements AS onProperty,
       statements AS f
     WHERE
       onProperty.predicate = 'owl:onProperty' AND
       onProperty.subject=f.subject AND
       f.predicate='owl:someValuesFrom';
CREATE VIEW rdf_type_statement AS SELECT * FROM statements WHERE predicate='rdf:type';
CREATE VIEW rdfs_label_statement AS SELECT * FROM statements WHERE predicate='rdfs:label';
CREATE VIEW rdfs_subclass_of_statement AS SELECT * FROM statements WHERE predicate='rdfs:subClassOf';
CREATE VIEW rdfs_subproperty_of_statement AS SELECT * FROM statements WHERE predicate='rdfs:subPropertyOf';
CREATE VIEW axiom_dbxref_annotation AS SELECT * FROM owl_axiom_annotation WHERE annotation_predicate = 'oio:hasDbXref';
CREATE VIEW class_node AS SELECT distinct subject AS id from rdf_type_statement WHERE object = 'owl:Class';
CREATE VIEW owl_subclass_of_some_values_from AS SELECT subClassOf.stanza,
         subClassOf.subject,
         svf.on_property AS predicate,
         svf.filler AS object
         FROM
    statements AS subClassOf, 
    owl_some_values_from AS svf
  WHERE
    subClassOf.predicate = 'rdfs:subClassOf' AND
    svf.id=subClassOf.object;
CREATE VIEW rdfs_subclass_of_named_statement AS SELECT * FROM rdfs_subclass_of_statement WHERE object NOT LIKE '_:%';
CREATE VIEW edge AS SELECT subject, predicate, object
  FROM owl_subclass_of_some_values_from
   UNION
  SELECT subject, predicate, object
  FROM rdfs_subclass_of_named_statement
   UNION
  SELECT subject, predicate, object
   FROM rdfs_subproperty_of_statement
   UNION
  SELECT subject, predicate, object
  FROM rdf_type_statement WHERE object IN (SELECT id FROM class_node);
