PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX chem: <https://w3id.org/chemschema/>
PREFIX type: <http://www.wikidata.org/prop/direct/P31>
PREFIX subClassOf: <http://www.wikidata.org/prop/direct/P279>
PREFIX Isotope: <http://www.wikidata.org/entity/Q25276>
PREFIX Element: <http://www.wikidata.org/entity/Q11344>
PREFIX symbol: <http://www.wikidata.org/prop/direct/P246>
PREFIX atomic_number: <http://www.wikidata.org/prop/direct/P1086>
PREFIX neutron_number: <http://www.wikidata.org/prop/direct/P1148>

CONSTRUCT {
    ?cls a owl:Class ;
         rdfs:label ?label ;
         owl:equivalentClass [
            owl:intersectionOf (
              r?element [
                 a owl:Restriction ;
                 owl:onProperty chem:charge ;
                 owl:hasValue ?charge
                 ])
         ]
}
WHERE {
    ?cls a chem:MonoatomicIon ;
         rdfs:label ?label ;
         chem:charge ?charge ;
         chem:has_element ?element .


}
